name: EggRenade
main: us.microapple.eggrenade.EggRenade
version: 2.1
commands:
  grenade:
    description: Toggles egg grenades
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command>
  molotov:
    description: Toggles egg molotov cocktails.
    usage: |
          Incorrect usage of /<command>. Exampled:
          /<command>